
services:
  dashboard:
    build: .
    container_name: streamlit_dashboard
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: ["bash", "start.sh"]
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped