services:
  dashboard:
    build: .
    container_name: streamlit_dashboard
    ports:
      - "9000:9000"  # Streamlit roda na porta 9000
      - "4040:4040"  # ngrok API local (opcional para debug)
    volumes:
      - .:/app
      - ./proxy_server:/proxy_server  # Monta pasta do Cloud SQL Proxy e credenciais
    command: ["bash", "/start.sh"]
    environment:
      - PYTHONUNBUFFERED=1
      - GOOGLE_APPLICATION_CREDENTIALS=/proxy_server/erpj-br-sql.json  # Padrão da lib do proxy
    restart: unless-stopped
