
[theme]
base="dark"
primaryColor="#08C0A9"
backgroundColor="#0E1117"
secondaryBackgroundColor="#dfd00ad5"
textColor="#FAFAFA"
font="sans serif"

[server]
headless = true
enableCORS = false

[client]
showSidebarNavigation = false

